name: habo
description: Minimalistic habit tracker.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.3+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6

  #Local Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2

  #UI
  table_calendar: ^3.0.9
  awesome_dialog: ^3.1.0
  loader_overlay: ^2.3.0
  introduction_screen: ^3.1.11
  fl_chart: ^0.63.0
  awesome_notifications: 0.8.2
  flutter_file_dialog: ^3.0.2

  #Audio
  just_audio: ^0.9.34
  just_audio_mpv: ^0.1.7
  
  #Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  equatable: ^2.0.5

  #Utils
  google_fonts: ^5.1.0
  fpdart: ^1.1.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  file_picker: ^5.3.3
  path_provider: ^2.1.0
  path: ^1.8.3
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  timezone: ^0.9.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For now mipmaps are used.
flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_icon.jpg"
  adaptive_icon_foreground: "assets/images/android_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/images/macos_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/sounds/
    - assets/google_fonts/
